<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8N7hwP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8N7hwP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerX8N7hwP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerX8N7hwP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerX8N7hwP\App_KernelProdContainer([
    'container.build_hash' => 'X8N7hwP',
    'container.build_id' => '680c3796',
    'container.build_time' => 1580896434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8N7hwP');
