<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin.product.index' => [[], ['_controller' => 'App\\Controller\\admin\\adminProductController::index'], [], [['text', '/admin']], [], []],
    'admin.product.edit' => [['id'], ['_controller' => 'App\\Controller\\admin\\adminProductController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\homeController::index'], [], [['text', '/']], [], []],
];
