<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoSzrOs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoSzrOs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoSzrOs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoSzrOs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIoSzrOs\App_KernelDevDebugContainer([
    'container.build_hash' => 'IoSzrOs',
    'container.build_id' => '9707a1e9',
    'container.build_time' => 1581269711,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoSzrOs');
