<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1jjcUKh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1jjcUKh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1jjcUKh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1jjcUKh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1jjcUKh\App_KernelDevDebugContainer([
    'container.build_hash' => '1jjcUKh',
    'container.build_id' => '015a2685',
    'container.build_time' => 1598013552,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1jjcUKh');
