<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[


], [

<<<<<<< HEAD
=======
0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/app.aa3a1d76.js',
            ],
            'css' => [
                '/build/app.9a410a72.css',
            ],
        ],
        'search' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/0.264d7ee1.js',
                '/build/search.7fd568cc.js',
            ],
        ],
        'toggleMenu' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/1.2131949b.js',
                '/build/toggleMenu.8bb70894.js',
            ],
        ],
        'searchCard' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/0.264d7ee1.js',
                '/build/searchCard.e469f61f.js',
            ],
        ],
        'updateMemo' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/updateMemo.2e95819a.js',
            ],
        ],
        'createSlug' => [
            'js' => [
                '/build/runtime.af19f1f9.js',
                '/build/1.2131949b.js',
                '/build/createSlug.a223d42c.js',
            ],
        ],
    ],
],
>>>>>>> Develop

]];
