<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.1103dde6.js',
                '/build/app.29caa2f3.js',
            ],
            'css' => [
                '/build/app.83405223.css',
            ],
        ],
        'search' => [
            'js' => [
                '/build/runtime.1103dde6.js',
                '/build/0.ecda7895.js',
                '/build/search.c1f21a8d.js',
            ],
        ],
        'toggleMenu' => [
            'js' => [
                '/build/runtime.1103dde6.js',
                '/build/1.d36e84db.js',
                '/build/toggleMenu.dbb759bb.js',
            ],
        ],
        'searchCard' => [
            'js' => [
                '/build/runtime.1103dde6.js',
                '/build/0.ecda7895.js',
                '/build/searchCard.05502178.js',
            ],
        ],
    ],
],

]];
