<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~app~frontModal~sortableSections.js',
                'http://localhost:8080/build/vendors~app~search~searchCard.js',
                'http://localhost:8080/build/vendors~app.js',
                'http://localhost:8080/build/app.js',
            ],
            'css' => [
                'http://localhost:8080/build/vendors~app.css',
                'http://localhost:8080/build/app.css',
            ],
        ],
        'sortableSections' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~frontModal~sortableSections.js',
                'http://localhost:8080/build/vendors~sortableSections.js',
                'http://localhost:8080/build/sortableSections.js',
            ],
        ],
        'search' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~app~search~searchCard.js',
                'http://localhost:8080/build/search.js',
            ],
        ],
        'toggleMenu' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~createSlug~toggleMenu.js',
                'http://localhost:8080/build/toggleMenu.js',
            ],
        ],
        'searchCard' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~app~search~searchCard.js',
                'http://localhost:8080/build/searchCard.js',
            ],
        ],
        'updateMemo' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/updateMemo.js',
            ],
        ],
        'createSlug' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~createSlug~toggleMenu.js',
                'http://localhost:8080/build/createSlug.js',
            ],
        ],
        'frontModal' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~app~createSlug~frontModal~search~searchCard~toggleMenu.js',
                'http://localhost:8080/build/vendors~app~frontModal~sortableSections.js',
                'http://localhost:8080/build/frontModal.js',
            ],
        ],
        'colorPicker' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/vendors~colorPicker.js',
                'http://localhost:8080/build/colorPicker.js',
            ],
        ],
        'onScroll' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~app~colorPicker~createSlug~frontModal~onScroll~search~searchCard~sortableSections~toggleMenu~722700c0.js',
                'http://localhost:8080/build/onScroll.js',
            ],
        ],
    ],
],

]];
